source 'http://rubygems.org'

gem 'bundler', '2.1.4'
gem 'concurrent-ruby', '1.1.7'
gem 'activerecord', '~> 6.0.3.3'
gem 'rouge'
gem 'pg'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'thin'
